//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.View.GuideView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.View.GuideView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iznad 50 godina:.
        /// </summary>
        internal static string Above {
            get {
                return ResourceManager.GetString("Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihvati.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji Profila.
        /// </summary>
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ako zelis da obrises kontrolnu tacku, odaberi je i pritisni dugme za brisanje.
        /// </summary>
        internal static string AddTourCheckpointInfo {
            get {
                return ResourceManager.GetString("AddTourCheckpointInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ako zelis da obrises datum, odaberi ga i pritisni dugme za brisanje.
        /// </summary>
        internal static string AddTourDateInfo {
            get {
                return ResourceManager.GetString("AddTourDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ako zelis da obrises sliku, odaberi je i pritisni dugme za brisanje.
        /// </summary>
        internal static string AddTourImageInfo {
            get {
                return ResourceManager.GetString("AddTourImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godine:.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi Obilasci.
        /// </summary>
        internal static string AllTours {
            get {
                return ResourceManager.GetString("AllTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovne Informacije.
        /// </summary>
        internal static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispod 18 godina:.
        /// </summary>
        internal static string Below {
            get {
                return ResourceManager.GetString("Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmedju 18 i 50 godina:.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritisnite ovde za brisanje .
        /// </summary>
        internal static string CancelTourClick {
            get {
                return ResourceManager.GetString("CancelTourClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapacitet:.
        /// </summary>
        internal static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolna tacka:.
        /// </summary>
        internal static string Checkpoint {
            get {
                return ResourceManager.GetString("Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolne Tacke.
        /// </summary>
        internal static string Checkpoints {
            get {
                return ResourceManager.GetString("Checkpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela ispod sadrzi listu svih kontrolnih tacaka.Zatamnjene tacke predstavljaju tacke koje su zavrsene.
        /// </summary>
        internal static string CheckpointTableInfo {
            get {
                return ResourceManager.GetString("CheckpointTableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar:.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksni Zahtevi.
        /// </summary>
        internal static string ComplexRequests {
            get {
                return ResourceManager.GetString("ComplexRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksni Zahtev.
        /// </summary>
        internal static string ComplexTourRequest {
            get {
                return ResourceManager.GetString("ComplexTourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksni Zahtevi.
        /// </summary>
        internal static string ComplexTourRequests {
            get {
                return ResourceManager.GetString("ComplexTourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi Slozeni Obilazak.
        /// </summary>
        internal static string CreateRequestedTour {
            get {
                return ResourceManager.GetString("CreateRequestedTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi Obilazak.
        /// </summary>
        internal static string CreateTour {
            get {
                return ResourceManager.GetString("CreateTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna Lokacija:.
        /// </summary>
        internal static string CurrentCheckpoint {
            get {
                return ResourceManager.GetString("CurrentCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna Tema.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datum.
        /// </summary>
        internal static string DateIcon {
            get {
                return ResourceManager.GetString("DateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datumi.
        /// </summary>
        internal static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis Obilaska:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opis.
        /// </summary>
        internal static string DescriptionIcon {
            get {
                return ResourceManager.GetString("DescriptionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje:.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavrsi Obilazak.
        /// </summary>
        internal static string EndTour {
            get {
                return ResourceManager.GetString("EndTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavrsene Ture.
        /// </summary>
        internal static string FinishedTours {
            get {
                return ResourceManager.GetString("FinishedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ime.
        /// </summary>
        internal static string FirstNameIcon {
            get {
                return ResourceManager.GetString("FirstNameIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generisi Statistiku.
        /// </summary>
        internal static string GenerateStatistics {
            get {
                return ResourceManager.GetString("GenerateStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodna Stranica.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena:.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodic.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GuideRankMainPage {
            get {
                return ResourceManager.GetString("GuideRankMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znanje vodica:.
        /// </summary>
        internal static string GuidesKnowledge {
            get {
                return ResourceManager.GetString("GuidesKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hej.
        /// </summary>
        internal static string Hey {
            get {
                return ResourceManager.GetString("Hey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slike.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vazno obavestenje.
        /// </summary>
        internal static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidno.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jezik.
        /// </summary>
        internal static string LanguageIcon {
            get {
                return ResourceManager.GetString("LanguageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prezime.
        /// </summary>
        internal static string LastNameIcon {
            get {
                return ResourceManager.GetString("LastNameIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla Tema.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritisnite za pracenje obilaska.
        /// </summary>
        internal static string LiveTourClick {
            get {
                return ResourceManager.GetString("LiveTourClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija:.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lokacija.
        /// </summary>
        internal static string LocationIcon {
            get {
                return ResourceManager.GetString("LocationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slike.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritisnite ovde za vise informacija.
        /// </summary>
        internal static string MoreInfoClick {
            get {
                return ResourceManager.GetString("MoreInfoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sledeca Lokacija.
        /// </summary>
        internal static string NextCheckpoint {
            get {
                return ResourceManager.GetString("NextCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj obilazaka:.
        /// </summary>
        internal static string NumberOfFinishedTours {
            get {
                return ResourceManager.GetString("NumberOfFinishedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Turista:.
        /// </summary>
        internal static string NumberOfTourists {
            get {
                return ResourceManager.GetString("NumberOfTourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , postoji jedan obilazak koji idalje traje, ne mozes da pokrenes drugi obilazak dok prethodni nije zavrsen.
        /// </summary>
        internal static string OngoingTourMessage {
            get {
                return ResourceManager.GetString("OngoingTourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostale Obilasci.
        /// </summary>
        internal static string OtherTours {
            get {
                return ResourceManager.GetString("OtherTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sveukupna Statistika.
        /// </summary>
        internal static string OverallStats {
            get {
                return ResourceManager.GetString("OverallStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite parametre i pritisnite &quot;pretraga&quot;.
        /// </summary>
        internal static string ParamsInfo {
            get {
                return ResourceManager.GetString("ParamsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ljudi.
        /// </summary>
        internal static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daj Otkaz.
        /// </summary>
        internal static string QuitJob {
            get {
                return ResourceManager.GetString("QuitJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvanje:.
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizacija:.
        /// </summary>
        internal static string Realisation {
            get {
                return ResourceManager.GetString("Realisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preporuceno:.
        /// </summary>
        internal static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevi.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restartuj Filter.
        /// </summary>
        internal static string ResetFilter {
            get {
                return ResourceManager.GetString("ResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenzije.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritisnite za prikaz svih recenzija.
        /// </summary>
        internal static string ReviewShowClick {
            get {
                return ResourceManager.GetString("ReviewShowClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizacija.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broj obilazaka.
        /// </summary>
        internal static string SegmentNumber {
            get {
                return ResourceManager.GetString("SegmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodicev jezik:.
        /// </summary>
        internal static string SpokenLanguage {
            get {
                return ResourceManager.GetString("SpokenLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapocnite Obilazak.
        /// </summary>
        internal static string StartTourClick {
            get {
                return ResourceManager.GetString("StartTourClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Vodic.
        /// </summary>
        internal static string SuperGuide {
            get {
                return ResourceManager.GetString("SuperGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tset.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema:.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najposecenija Tura.
        /// </summary>
        internal static string TheMostVisitedTour {
            get {
                return ResourceManager.GetString("TheMostVisitedTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danasnji Obilasci.
        /// </summary>
        internal static string TodaysTours {
            get {
                return ResourceManager.GetString("TodaysTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znamenitosti obilaska:.
        /// </summary>
        internal static string TourAttractions {
            get {
                return ResourceManager.GetString("TourAttractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delovi Zahteva.
        /// </summary>
        internal static string TourFragments {
            get {
                return ResourceManager.GetString("TourFragments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidencija Turista.
        /// </summary>
        internal static string TouristEvidence {
            get {
                return ResourceManager.GetString("TouristEvidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupan Broj Turista.
        /// </summary>
        internal static string TouristNumber {
            get {
                return ResourceManager.GetString("TouristNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turisti.
        /// </summary>
        internal static string Tourists {
            get {
                return ResourceManager.GetString("Tourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turisti.
        /// </summary>
        internal static string TouristsIcon {
            get {
                return ResourceManager.GetString("TouristsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznacite turistu koji se pojavio na trenutnoj kontrolnoj tacki, ukoliko nema ni 1 novi turista,predji na sledeci checkpoint.
        /// </summary>
        internal static string TouristTableInfo {
            get {
                return ResourceManager.GetString("TouristTableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Realizacije:.
        /// </summary>
        internal static string TourRealisationDate {
            get {
                return ResourceManager.GetString("TourRealisationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datumi Realizacije:.
        /// </summary>
        internal static string TourRealisations {
            get {
                return ResourceManager.GetString("TourRealisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevi za Obilaske .
        /// </summary>
        internal static string TourRequests {
            get {
                return ResourceManager.GetString("TourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obilasci.
        /// </summary>
        internal static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validno.
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik sajta:.
        /// </summary>
        internal static string WebsiteLanguage {
            get {
                return ResourceManager.GetString("WebsiteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
